name: 🤖🆙❄️
on:
  pull_request:
    paths:
      - '.github/workflows/bump-flake-lock-and-selfup.yml'
  schedule:
    # At 10:17 JST on day-of-month 1 and on Monday.
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    # You can understand the config actually say what in https://crontab.guru/
    - cron: '17 1 1 * 1'
  workflow_dispatch:

jobs:
  bump:
    uses: kachick/selfup/.github/workflows/reusable-bump-flake-lock-and-selfup.yml@88891fc4bcc2e39ac38c01aff690f2e9b4e33c80 # v1.1.2
    with:
      dry-run: ${{ github.event_name == 'pull_request' }}
      pr-title: 'Bump flake.lock and related dependencies'
      optional-run: |
        echo 'Add another changes and git commit here, especially for .node-version/.ruby-version'
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
