on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.20"

    - name: Install yamlfmt
      run: go install github.com/google/yamlfmt/cmd/yamlfmt@v0.10.0

    - name: Install dependencies
      run: npm ci --ignore-scripts

    - name: Run dummy tests
      run: xvfb-run -a npm test
      continue-on-error: true

    - name: Run tests
      run: xvfb-run -a npm test
